---
dotfiles_repo: 'https://github.com/dochang/dotfiles.git'
dotfiles_http_proxy: ''
dotfiles_https_proxy: ''
dotfiles_editor: vi
dotfiles_name: 'Desmond O. Chang'
dotfiles_email: dochang@gmail.com
dotfiles_mailuser: dochang
dotfiles_mailhost: localhost
dotfiles_maildir: /srv/sync/maildir
dotfiles_password_store_dir: '${HOME}/.password-store'
dotfiles_git_credential: dochang
dotfiles_git_user_name: '{{ dotfiles_name }}'
dotfiles_git_user_email: '{{ dotfiles_email }}'
dotfiles_linuxbrew_prefix: /home/linuxbrew/.linuxbrew
dotfiles_emacs_name: '{{ dotfiles_name }}'
dotfiles_emacs_email: '{{ dotfiles_email }}'
dotfiles_emacs_package_archives:
  - id: gnu
    location: https://elpa.gnu.org/packages/
  - id: melpa
    location: https://melpa.org/packages/
  - id: org
    location: http://orgmode.org/elpa/
  - id: melpa-stable
    location: https://stable.melpa.org/packages/

  # Downloading marmalade archive will cause Emacs hangs at 100% CPU usage.
  # Disable it for now.  See nicferrier/elmarmalade#106 .
  #
  # - id: marmalade
  #   location: https://marmalade-repo.org/packages/

  # Disable the following archives.  Their packages are too old.
  #
  # - id: ELPA
  #   location: http://tromey.com/elpa/

  # Disable it
  #
  # https://github.com/escherdragon/sunrise-commander/issues/57
  #
  # - id: SC
  #   location: http://joseito.republika.pl/sunrise-commander/
dotfiles_emacs_holiday_other_holidays: []
dotfiles_i3status_netdev_type: wireless
dotfiles_i3status_netdev: wlan0
dotfiles_i3status_vm_enabled: yes
dotfiles_nix_nixpkgs_channel_url: https://nixos.org/channels/nixpkgs-unstable
dotfiles_pip_index_url: https://pypi.org/simple
dotfiles_npm_registry: https://registry.npmjs.org/
dotfiles_npm_disturl: https://nodejs.org/dist
dotfiles_node_build_mirror_url: https://nodejs.org/dist
dotfiles_yarn_registry: https://registry.yarnpkg.com
dotfiles_gem_source: https://rubygems.org/
dotfiles_rustup_dist_server: https://static.rust-lang.org
dotfiles_rustup_update_root: https://static.rust-lang.org/rustup
dotfiles_cargo_default_config: {}
dotfiles_cargo_config:
  source:
    crates-io:
      registry: https://github.com/rust-lang/crates.io-index
dotfiles_arduinoide_preferences:
  - line: 'editor.linenumbers=true'
    regexp: 'editor\.linenumbers='
dotfiles_maven_mirrors: []
dotfiles_pbuilder_mirrorsite: 'http://deb.debian.org/debian'
