---
- hosts: 'all'
  sudo: yes

  vars:
    pkg_state: present

  tasks:

    - name: Install Android SDK
      shell: wget -O - http://dl.google.com/android/android-sdk_r24.1.2-linux.tgz | tar xzf -
      args:
        chdir: /opt
        creates: '/opt/android-sdk-linux'

    - name: Get user primary group name
      getent:
        database: group
        key: '{{ (ansible_env["SUDO_GID"] | default("")) or ansible_user_gid }}'

    - name: Fix ownership for /opt/android-sdk-linux
      file:
        path: /opt/android-sdk-linux
        owner: '{{ ansible_ssh_user }}'
        group: '{{ getent_group.keys()[0] }}'
        recurse: yes
        state: directory

    - name: Install Gradle
      nix_env:
        name: gradle
        state: '{{ pkg_state }}'

    - name: Install android-udev-rules
      nix_env:
        name: android-udev-rules
        state: '{{ pkg_state }}'
      sudo: yes
      sudo_user: '{{ ansible_ssh_user }} -i'
      register: udev_rules

    - name: Symlink android-udev-rules
      file:
        path: /etc/udev/rules.d/51-android.rules
        src: /nix/var/nix/profiles/default/lib/udev/rules.d/51-android.rules
        state: link
      register: link_rules
      notify:
        - reload udev
      changed_when: udev_rules.changed or link_rules.changed

    - name: Add i386 arch for Debian
      command: dpkg --add-architecture i386

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install packages that Android SDK depends on
      apt:
        name: '{{ item }}'
        state: present
      environment:
        APT_LISTCHANGES_FRONTEND: none
        APT_LISTBUGS_FRONTEND: none
      with_items:
        - libncurses5:i386
        - libstdc++6:i386
        - zlib1g:i386
        - default-jdk

  handlers:
    - name: reload udev
      service:
        name: udev
        state: reloaded
        use_service: prefer
