---
kind: pipeline
type: docker
name: Mega-Linter
workspace:
  path: /drone/src
steps:
  - name: Lint
    image: 'nvuillam/mega-linter:v4'
    environment:
      DEFAULT_WORKSPACE: /drone/src

---
kind: pipeline
type: docker
name: default
workspace:
  path: /drone/src/ansible_collections/dochang/dotfiles
steps:
  - name: Sanity-Test
    image: 'python:latest'
    commands:
      - python -m pip install --upgrade pip
      - python -m pip install --upgrade pipx
      - python -m pipx ensurepath
      - python -m pipx run --spec ansible ansible-test sanity --local
    environment:
      ANSIBLE_COLLECTIONS_PATH: /drone/src
