---
- hosts: all

  vars_files:
    - vars/androidsdk/main.yml
    -
      - 'vars/androidsdk/installer/{{ ansible_system }}/main.yml'
      - 'vars/androidsdk/installer/default.yml'

  become: yes
  become_user: root

  roles:

    - role: archivepkg
      archivepkg_package_filename: '{{ androidsdk_package_filename }}'
      archivepkg_package_url: '{{ androidsdk_package_url }}'
      archivepkg_package_checksum: '{{ androidsdk_package_checksums[androidsdk_version][androidsdk_system] }}'
      archivepkg_topdir: '{{ androidsdk_package_topdir }}'
      archivepkg_dest: '{{ androidsdk_install_dir }}'

  tasks:

    - name: Fix ownership
      file:
        path: '{{ androidsdk_install_dir }}'
        state: directory
        group: '{{ hostvars[inventory_hostname].ansible_user }}'
        owner: '{{ hostvars[inventory_hostname].ansible_user }}'
        recurse: yes
