#!/bin/sh

venv=~/.local/venvs/ansible
[ ! -d "${venv}" ] || find "${venv}" -type l -delete
virtualenv "${venv}"
. "${venv}/bin/activate"
pip install -U ansible
hash -r

export ANSIBLE_EXECUTABLE='/bin/bash -l'
export ANSIBLE_ROLES_PATH="${venv}/roles"

ansible-galaxy install --role-file=requirements.yml
ansible --ask-sudo-pass -vvv "$@"
