#!/bin/sh

venv=~/.local/venvs/ansible
[ ! -d "${venv}" ] || find "${venv}" -type l -delete
virtualenv "${venv}"
"${venv}/bin/pip" install -U ansible
hash -r
export ANSIBLE="${venv}/bin/ansible"

export ANSIBLE_EXECUTABLE='/bin/bash -l'

"${ANSIBLE}" --ask-sudo-pass -vvv "$@"
