#!/bin/sh

export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-${HOME}/.config}
export SYSTEMD_USER_DIR=${XDG_CONFIG_HOME}/systemd/user

find "${SYSTEMD_USER_DIR}" -name '*.service' -printf '%P\n' | {
	while read REPLY ; do
		systemctl --user stop "${REPLY}"
		case "${REPLY}" in
		gpg-agent.service)
			systemctl --user disable "${REPLY}"
			;;
		esac
		rm -f "${SYSTEMD_USER_DIR}/${REPLY}"
	done
}
