---
- hosts: all

  vars_files:
    - vars/doctl/main.yml
    -
      - 'vars/doctl/installer/{{ ansible_system }}/{{ ansible_architecture }}/main.yml'
      - 'vars/doctl/installer/{{ ansible_system }}/main.yml'
      - 'vars/doctl/installer/default.yml'

  roles:

    - role: binpkg
      binpkg_package_filename: '{{ doctl_package_filename }}'
      binpkg_package_url: '{{ doctl_package_url }}'
      binpkg_package_checksum: '{{ doctl_package_checksums[doctl_version][doctl_platform] }}'
      binpkg_binaries:
        - src: doctl
      binpkg_dest: ~/bin
