---
- hosts: all

  vars_files:
    - vars/ipfs/main.yml
    -
      - 'vars/ipfs/installer/{{ ansible_system }}/{{ ansible_architecture }}/main.yml'
      - 'vars/ipfs/installer/{{ ansible_system }}/main.yml'
      - 'vars/ipfs/installer/main.yml'

  roles:

    - role: binpkg
      binpkg_package_filename: '{{ ipfs_package_filename }}'
      binpkg_package_url: '{{ ipfs_package_url }}'
      binpkg_package_checksum: '{{ ipfs_package_checksums[ipfs_version][ipfs_platform] }}'
      binpkg_binaries:
        - src: go-ipfs/ipfs
      binpkg_dest: ~/bin
