---
- hosts: all

  vars:
    ansible_shell_executable: '/bin/bash -l'

  tasks:

    - import_role:
        name: rustup
      tags:
        - rust

    - name: create /home/linuxbrew
      file:
        path: /home/linuxbrew
        mode: '700'
        group: '{{ ansible_user }}'
        owner: '{{ ansible_user }}'
        state: directory
      become: yes
      become_user: root

    - import_role:
        name: userconfig
