---
- name: include os specific variables
  include_vars: 'installer/{{ ansible_system }}/main.yml'

- name: set facts for installing android sdk
  set_fact:
    # A variable evaluates the random filter in its value every time.  Solve it
    # by setting the value to a fact.
    #
    # https://opensolitude.com/2015/05/27/ansible-lookups-variables-vs-facts.html
    # https://stackoverflow.com/a/28490160
    androidsdk_cache_dir: '{{ androidsdk_cache_prefix }}/ansible-androidsdk-{{ ansible_user_uid }}-{{ ansible_date_time.epoch }}-{{ (2**48) | random }}'
    androidsdk_package_pathname: '{{ androidsdk_download_dir }}/{{ androidsdk_package_filename }}'

- name: check if android sdk installed
  command: 'ls {{ androidsdk_install_dir }}'
  register: androidsdk_install_dir_list
  ignore_errors: yes
  changed_when: false
  always_run: yes

- include: install.yml
  when: 'androidsdk_install_dir_list.stdout_lines | length == 0'
