- name: set dest
  set_fact:
    dest: '{{ item.dest | default("~/." ~ item.src) }}'

- name: create directory
  file:
    path: '{{ dest | dirname }}'
    state: directory
    mode: '700'

- name: install dotfile
  template:
    dest: '{{ dest }}'
    src: '{{ item.src }}'
    mode: '{{ item.mode | default("600") }}'
