- name: ensure directory present
  file:
    path: '{{ dest | dirname }}'
    state: directory
    mode: '700'
  when: 'dest | dirname | expanduser | realpath != ansible_user_dir'

- name: install dotfile
  template:
    dest: '{{ dest }}'
    src: '{{ item }}'
    mode: '{{ mode | default("600") }}'
  with_first_found:
    - files:
        - '{{ src }}.{{ inventory_hostname }}'
        - '{{ src }}.{{ inventory_hostname | regex_replace("^[^\.]*(\.|$)", "") }}'
        - '{{ src }}'
