- include_tasks: dotdir.yml
  with_items:
    - src: 'emacs/packages.el'
      dest: '~/.emacs.d/packages.el'
    - src: 'emacs/bootstrap.el'
      dest: '~/.emacs.d/bootstrap.el'
    - src: 'emacs/init.el'
      dest: '~/.emacs.d/init.el'
    - src: 'gnus/gnus.el'
      dest: '~/.gnus.el'

- name: ensure ~/.emacs.d/{{ item }} present
  file:
    path: '~/.emacs.d/{{ item }}'
    state: directory
  with_items:
    - init.d
    - site-lisp
    - themes

- name: install emacs site files
  synchronize:
    dest: '~/.emacs.d/{{ item }}/'
    src: 'emacs/{{ item }}/'
    partial: no
    delete: yes
  with_items:
    - site-lisp
    - themes

- name: install emacs enabled init files
  synchronize:
    dest: '~/.emacs.d/init.d/'
    src: 'emacs/init.enabled.d/'
    partial: no
    delete: yes

- name: install emacs init template files
  template:
    dest: '~/.emacs.d/init.d/{{ item | basename }}'
    src: '{{ item }}'
  with_fileglob:
    - emacs/init.template.d/*.el

- name: install emacs disabled init files
  file:
    name: '~/.emacs.d/init.d/{{ item | basename }}'
    state: absent
  with_fileglob:
    - emacs/init.disabled.d/*.el
