- include: dotdir.yml
  with_items:
    - src: 'emacs/packages.el'
      dest: '~/.emacs.d/packages.el'
    - src: 'emacs/init.el'
      dest: '~/.emacs.d/init.el'
    - src: 'emacs/chinese-fonts-setup/v3/default.el'
      dest: '~/.emacs.d/chinese-fonts-setup/v3/default.el'
    - src: 'gnus/gnus.el'
      dest: '~/.gnus.el'

- name: ensure ~/.emacs.d/{{ item }} present
  file:
    path: '~/.emacs.d/{{ item }}'
    state: directory
  with_items:
    - init.d
    - site-lisp
    - themes

- name: install emacs *.el files
  copy:
    dest: '~/.emacs.d/{{ item | relpath("emacs") }}'
    src: '{{ item }}'
  with_fileglob:
    - emacs/init.d/*.el
    - emacs/site-lisp/*.el
    - emacs/themes/*.el
