- include_tasks: dotdir.yml
  with_items:
    - src: 'emacs/theme.el'
      dest: '~/.emacs.d/theme.el'
    - src: 'emacs/packages.el'
      dest: '~/.emacs.d/packages.el'
    - src: 'emacs/bootstrap.el'
      dest: '~/.emacs.d/bootstrap.el'
    - src: 'emacs/use-package.el'
      dest: '~/.emacs.d/use-package.el'
    - src: 'emacs/quelpa.el'
      dest: '~/.emacs.d/quelpa.el'
    - src: 'emacs/req-package.el'
      dest: '~/.emacs.d/req-package.el'
    - src: 'emacs/load-dir.el'
      dest: '~/.emacs.d/load-dir.el'
    - src: 'emacs/init.el'
      dest: '~/.emacs.d/init.el'
    - src: 'gnus/gnus.el'
      dest: '~/.gnus.el'

- name: ensure ~/.emacs.d/{{ item }} present
  file:
    path: '~/.emacs.d/{{ item }}'
    state: directory
  with_items:
    - init.d
    - site-lisp
    - themes

- name: install emacs site files
  synchronize:
    dest: '~/.emacs.d/{{ item }}/'
    src: 'emacs/{{ item }}/'
    partial: no
    delete: yes
  with_items:
    - init.d
    - site-lisp
    - themes

- name: install emacs init template files
  template:
    dest: '~/.emacs.d/init.d/{{ item }}.el'
    src: 'emacs/init.d/{{ item }}.el'
  with_items:
    - emacs

- name: remove emacs disabled init files
  file:
    name: '~/.emacs.d/init.d/{{ item | basename }}'
    state: absent
  with_fileglob:
    - emacs/init.disabled.d/*.el
