---
- name: ensure home present
  file:
    path: '{{ dotfiles_home }}'
    state: directory

- name: ensure xdg config home present
  file:
    path: '{{ dotfiles_xdg_config_home }}'
    state: directory

- include_tasks: outer_loop.yml
  loop: '{{ dotfiles_dotfiles }}'
  loop_control:
    loop_var: outer_item
