---
- name: sync files
  synchronize:
    dest: '{{ fulldest }}'
    src: '{{ entry.src }}'
    partial: false
    delete: true
    times: true
    rsync_opts:
      - '--chmod={{ mode }}'
  notify: '{{ entry.notify | default(omit) }}'
