---
- name: enable syncthing systemd system service
  command: 'systemctl enable syncthing@{{ item }}.service'
  with_items: '{{ syncthing_server_users or [] }}'

- name: ensure syncthing systemd system service started
  command: 'systemctl start syncthing@{{ item }}.service'
  with_items: '{{ syncthing_server_users or [] }}'

- name: enable syncthing systemd user service
  command: 'systemctl --user enable syncthing.service'
  with_items: '{{ syncthing_desktop_users or [] }}'

- name: ensure syncthing systemd user service started
  command: 'systemctl --user start syncthing.service'
  with_items: '{{ syncthing_desktop_users or [] }}'
