---
- name: enable syncthing systemd system service
  systemd:
    name: 'syncthing@{{ item }}.service'
    enabled: yes
  with_items: '{{ syncthing_server_users or [] }}'

- name: ensure syncthing systemd system service started
  systemd:
    name: 'syncthing@{{ item }}.service'
    state: started
  with_items: '{{ syncthing_server_users or [] }}'

- name: enable syncthing systemd user service
  systemd:
    name: 'syncthing.service'
    user: yes
    enabled: yes
  with_items: '{{ syncthing_desktop_users or [] }}'

- name: ensure syncthing systemd user service started
  systemd:
    name: 'syncthing.service'
    user: yes
    state: started
  with_items: '{{ syncthing_desktop_users or [] }}'
