---

# https://github.com/rust-lang/cargo/issues/2082
- name: Install/Upgrade Rust packages
  command: >-
    cargo
    {{ (pkg_state == "latest") | ternary("install-update", "install") }}
    {{ item }}
  with_items:
    - '{{ envs.rust_packages }}'
