---

# https://github.com/rubygems/rubygems/issues/1668#issuecomment-233343395
# https://stackoverflow.com/a/40150951
- name: Update installed gems
  command: '{{ item }}'
  with_items:
    - gem update --system
    - gem update

- name: Install utils
  gem:
    name: '{{ item.1 }}'
    state: '{{ pkg_state }}'
  environment:
    RBENV_VERSION: '{{ item.0 }}'
  notify:
    - rbenv rehash
  with_nested:
    - '{{ envs.rbenv.versions }}'
    - '{{ envs.rbenv.packages }}'
