---

- name: Install utils
  command: >-
    go get
    {{ (pkg_state == "latest") | ternary("-u", "") }}
    {{ item.1 }}
  environment:
    GOENV_VERSION: '{{ item.0 }}'
    CGO_ENABLED: 0
  notify:
    - goenv rehash
  with_nested:
    - '{{ envs.goenv.versions }}'
    - '{{ envs.goenv.packages }}'
