---

- name: Install utils
  command: >-
    go get
    {{ (pkg_state == "latest") | ternary("-u", "") }}
    {{ item.1 }}
  environment:
    CGO_ENABLED: 0
  notify:
    - goenv rehash

- name: Install go linters
  command: >-
    gometalinter --install
    {{ (pkg_state == "latest") | ternary("--update", "") }}
  environment:
    CGO_ENABLED: 0
  notify:
    - goenv rehash
