---
- name: Install utils
  command: >-
    go get
    {{ (pkg_state == "latest") | ternary("-u", "") }}
    {{ item }}
  environment:
    GOENV_VERSION: system
    CGO_ENABLED: 0
    GO111MODULE: off
  with_items:
    - '{{ envs.go_legacy_packages }}'

- name: Install go mod utils
  command: >-
    go get
    {{ (pkg_state == "latest") | ternary("-u", "") }}
    {{ item }}
  environment:
    GOENV_VERSION: system
    CGO_ENABLED: 0
    GO111MODULE: on
  with_items:
    - '{{ envs.go_packages }}'
