---
- name: retrieve status of /home/linuxbrew
  stat:
    path: /home/linuxbrew
    get_attributes: yes
  register: linuxbrew_home_stat

- name: set linuxbrew_prefix
  set_fact:
    linuxbrew_prefix: /home/linuxbrew/.linuxbrew
  when: linuxbrew_home_stat.writeable

- name: set linuxbrew_prefix
  set_fact:
    linuxbrew_prefix: '~/.linuxbrew'
  when: not linuxbrew_home_stat.writeable

- name: set linuxbrew_repository
  set_fact:
    linuxbrew_repository: '{{ linuxbrew_prefix }}/Homebrew'

- name: install Linuxbrew
  git:
    dest: '{{ linuxbrew_repository }}'
    repo: https://github.com/Homebrew/brew.git
    update: no

- name: symlink bin/brew
  file:
    path: '{{ linuxbrew_prefix }}/bin/brew'
    src: '{{ linuxbrew_repository }}/bin/brew'
    state: link

- name: install vendor dependencies
  command: 'brew vendor-install {{ item }}'
  with_items:
    - ruby

- name: update Linuxbrew
  homebrew:
    update_homebrew: yes
  when: pkg_state == 'latest'

- name: tap Homebrew repositories
  homebrew_tap:
    tap: '{{ item }}'
    state: present
  environment:
    HOMEBREW_DEVELOPER: 1
    # I have to enable this variable because I don't want to clone the taps as
    # shallow.  I can pass `--full` but it's boring.
    #
    # https://github.com/Homebrew/brew/blob/1.7.6/Library/Homebrew/cmd/tap.rb#L62
  with_items:
    - beeftornado/rmtree
    - dochang/binary
    - dochang/tap
    - Linuxbrew/fonts

# https://github.com/xtaniguchimasaya/homebrew-fonts#working-with-fontconfig
# https://dev.to/xtaniguchimasaya/linuxbrew-as-a-font-manager-5af2
- name: ensure {{ linuxbrew_prefix }}/share/fonts present
  file:
    path: '{{ linuxbrew_prefix }}/share/fonts'
    state: directory

- name: symlink fonts directory
  file:
    path: '~/.local/share/fonts'
    src: '{{ linuxbrew_prefix }}/share/fonts'
    state: link

- name: install/upgrade Linuxbrew packages
  homebrew:
    name: '{{ item }}'
    state: '{{ pkg_state }}'
  environment:
    HOMEBREW_DEVELOPER: 1
    # I have to enable this variable because I don't want to clone the taps as
    # shallow.  I can pass `--full` but it's boring.
    #
    # https://github.com/Homebrew/brew/blob/1.7.6/Library/Homebrew/cmd/tap.rb#L62
  with_items:
    - dochang/binary/flarectl
    - dochang/binary/git-annex
    - git-extras
    - go
    - pandoc
    - rclone
    - restic
    - the_silver_searcher
    - yarn
    - dep
    - govendor
    - go-bindata
    # The original project is deprecated.  The original author has deleted its
    # account.  The user `jteeuwen` is a newly registered user. [1]
    #
    # [1]: https://github.com/jteeuwen/go-bindata/issues/5
    #
    # Active, notable forks are:
    #
    #  1. https://github.com/kevinburke/go-bindata
    #  2. https://github.com/go-bindata/go-bindata
    #  3. https://github.com/tmthrgd/go-bindata
    #  4. https://github.com/lestrrat-go/bindata
    #
    # We use 1 because Homebrew and Linuxbrew use it.
    - direnv
    - devd
    - modd
    - git-appraise
    - doctl
    - vultr
    - warp
    - git-sizer
    - piknik
    - dochang/tap/croc
    - dochang/binary/gometalinter
    - ripgrep
    - xsv
    - shellcheck
    - editorconfig
    - progress
    - jq
    - jo
    - shfmt
    - shyiko/ktlint/ktlint
