---

- name: retrieve status of /home/linuxbrew
  stat:
    path: /home/linuxbrew
    get_attributes: yes
  register: linuxbrew_home_stat

- name: set linuxbrew_prefix
  set_fact:
    linuxbrew_prefix: /home/linuxbrew/.linuxbrew
  when: linuxbrew_home_stat.writeable

- name: set linuxbrew_prefix
  set_fact:
    linuxbrew_prefix: '~/.linuxbrew'
  when: not linuxbrew_home_stat.writeable

- name: set linuxbrew_repository
  set_fact:
    linuxbrew_repository: '{{ linuxbrew_prefix }}/Homebrew'

- name: install Linuxbrew
  git:
    dest: '{{ linuxbrew_repository }}'
    repo: https://github.com/Linuxbrew/brew.git
    update: no

- name: symlink bin/brew
  file:
    path: '{{ linuxbrew_prefix }}/bin/brew'
    src: '{{ linuxbrew_repository }}/bin/brew'
    state: link

- name: install vendor dependencies
  command: 'brew vendor-install {{ item }}'
  with_items:
    - ruby

- name: update Linuxbrew
  homebrew:
    update_homebrew: yes
  when: pkg_state == 'latest'

- name: tap Homebrew repositories
  homebrew_tap:
    tap: '{{ item }}'
    state: present
  environment:
    HOMEBREW_DEVELOPER: 1
    # I have to enable this variable because I don't want to clone the taps as
    # shallow.  I can pass `--full` but it's boring.
    #
    # https://github.com/Linuxbrew/brew/blob/1.7.6/Library/Homebrew/cmd/tap.rb#L62
  with_items:
    - beeftornado/rmtree
    - dochang/binary

- name: install/upgrade Linuxbrew packages
  homebrew:
    name: '{{ item }}'
    state: '{{ pkg_state }}'
  with_items:
    - heroku
    - proxychains-ng
    - dochang/binary/ipfs
    - dochang/binary/terraform
    - dochang/binary/jid
    - dochang/binary/hugo
    - dochang/binary/arduino
    - go
    - yarn
    - dochang/binary/whalebrew
    - dochang/binary/wuzz
    - dochang/binary/peco
    - dochang/binary/sift
    - dochang/binary/git-annex
    - dochang/binary/lnav
    - yank
    - pandoc
    - dochang/binary/flarectl
    - git-extras
    - restic
    - the_silver_searcher
