---

- name: install Linuxbrew
  git:
    dest: ~/.linuxbrew
    repo: https://github.com/Linuxbrew/brew.git
    update: no

- name: update Linuxbrew
  homebrew:
    update_homebrew: yes
  when: pkg_state == 'latest'

- name: tap Homebrew repositories
  homebrew_tap:
    tap: '{{ item }}'
    state: present
  with_items:
    - beeftornado/rmtree
    - dochang/binary

- name: install/upgrade Linuxbrew packages
  homebrew:
    name: '{{ item }}'
    state: '{{ pkg_state }}'
  with_items:
    - heroku
    - proxychains-ng
    - dochang/binary/ipfs
    - dochang/binary/terraform
    - dochang/binary/jid
    - dochang/binary/hugo
    - dochang/binary/arduino
    - dochang/binary/go
    - dochang/binary/yarn
    - dochang/binary/whalebrew
    - dochang/binary/wuzz
    - dochang/binary/peco
    - dochang/binary/piknik
    - dochang/binary/sift
    - dochang/binary/git-annex
    - dochang/binary/lnav
    - yank
    - dochang/binary/pandoc
    - dochang/binary/flarectl
    - git-extras
    - dochang/binary/restic
