---

- name: install Linuxbrew
  git:
    dest: ~/.linuxbrew
    repo: https://github.com/Linuxbrew/brew.git
    update: no

- name: update Linuxbrew
  homebrew:
    update_homebrew: yes
  when: pkg_state == 'latest'

- name: tap Homebrew repositories
  homebrew_tap:
    tap: '{{ item }}'
    state: present
  with_items:
    - beeftornado/rmtree
    - dochang/binary

- name: install/upgrade Linuxbrew packages
  homebrew:
    name: '{{ item }}'
    state: '{{ pkg_state }}'
  with_items:
    - beeftornado/rmtree/brew-rmtree
    - heroku
    - proxychains-ng
    - dochang/binary/ipfs
    - dochang/binary/terraform
    - dochang/binary/doctl
    - dochang/binary/jid
    - dochang/binary/hugo
    - dochang/binary/arduino
    - dochang/binary/go
