---

- name: Install utils
  yarn:
    name: '{{ item }}'
    global: yes
    production: yes
    state: '{{ pkg_state }}'
  notify:
    - nodenv rehash
  with_items:
    - '{{ envs.nodenv.packages }}'
