---
- name: config docker
  copy:
    dest: /etc/systemd/system/docker.service.d/
    src: etc/systemd/system/docker.service.d/
    group: root
    owner: root
    mode: '644'
    directory_mode: '755'
  notify:
    - reload systemd
    - restart docker

- name: ensure /etc/docker present
  file:
    path: /etc/docker
    group: root
    owner: root
    mode: '700'
    state: directory

- name: config dockerd
  template:
    dest: '/etc/docker/daemon.json'
    src: 'etc/docker/daemon.json'
    group: root
    owner: root
    mode: '600'
  notify:
    - restart docker
