---
- include: apt.yml

- include: datetime.yml

- include: alternatives.yml

- include: postfix.yml

- name: enable auto-hibernate of laptop-mode-tools
  lineinfile:
    dest: /etc/laptop-mode/conf.d/auto-hibernate.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
  with_items:
    - regexp: '^[ \t]*ENABLE_AUTO_HIBERNATION='
      line: 'ENABLE_AUTO_HIBERNATION=1'
    - regexp: '^[ \t]*AUTO_HIBERNATION_BATTERY_CHARGE_PERCENT='
      line: 'AUTO_HIBERNATION_BATTERY_CHARGE_PERCENT=10'
    - regexp: '^[ \t]*AUTO_HIBERNATION_ON_CRITICAL_BATTERY_LEVEL='
      line: 'AUTO_HIBERNATION_ON_CRITICAL_BATTERY_LEVEL=1'

- name: always ask for the hostname when reboot, poweroff, etc.
  lineinfile:
    dest: /etc/molly-guard/rc
    regexp: '^[ \t]*ALWAYS_QUERY_HOSTNAME='
    line: 'ALWAYS_QUERY_HOSTNAME=true'
    state: present

- name: disable system-wide unclutter startup script
  # use my own version instead
  lineinfile:
    path: /etc/default/unclutter
    regexp: '^[ \t]*START_UNCLUTTER='
    line: 'START_UNCLUTTER=false'
    state: present

- include: docker.yml
  tags:
    - docker

- include: syncthing.yml

- include: android-udev-rules.yml
