---
- import_tasks: apt.yml

- import_tasks: datetime.yml

- import_tasks: alternatives.yml

- import_tasks: postfix.yml

- name: enable auto-hibernate of laptop-mode-tools
  lineinfile:
    dest: /etc/laptop-mode/conf.d/auto-hibernate.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
  with_items:
    - regexp: '^[ \t]*ENABLE_AUTO_HIBERNATION='
      line: 'ENABLE_AUTO_HIBERNATION=1'
    - regexp: '^[ \t]*AUTO_HIBERNATION_BATTERY_CHARGE_PERCENT='
      line: 'AUTO_HIBERNATION_BATTERY_CHARGE_PERCENT=10'
    - regexp: '^[ \t]*AUTO_HIBERNATION_ON_CRITICAL_BATTERY_LEVEL='
      line: 'AUTO_HIBERNATION_ON_CRITICAL_BATTERY_LEVEL=1'

- name: always ask for the hostname when reboot, poweroff, etc.
  lineinfile:
    dest: /etc/molly-guard/rc
    regexp: '^[ \t]*ALWAYS_QUERY_HOSTNAME='
    line: 'ALWAYS_QUERY_HOSTNAME=true'
    state: present

- import_tasks: X.yml

- import_tasks: docker.yml
  tags:
    - docker

- import_tasks: syncthing.yml

- import_tasks: android-udev-rules.yml
