#!/usr/bin/env python

from __future__ import unicode_literals

from functools import cmp_to_key
import json
import sys


def get_output_config(output, query, last_config):
    q = query[output]
    preferred = q.get('preferred') or q['modes'][0]
    width = preferred['width']
    height = preferred['height']
    rate = preferred['rate']
    if output == 'LVDS1':
        return {
            'x': 0,
            'y': 0,
            'width': width,
            'height': height,
            'rate': rate,
        }
    elif output == 'VIRTUAL1':
        return {
            'x': query['LVDS1']['preferred']['width'],
            'y': query['LVDS1']['preferred']['height'],
            'width': width,
            'height': height,
            'rate': rate,
        }


def get_config(query):
    config = {}

    def connected(output):
        return query[output]['connected']

    def index(output):
        return query[output]['index']

    def cmp(x, y):
        if connected(x) and not connected(y):
            return -1
        if not connected(x) and connected(y):
            return 1
        return index(x) - index(y)

    outputs = sorted(query.keys(), key=cmp_to_key(cmp))
    outputs = ['VIRTUAL1', 'LVDS1']
    last_config = None
    for output in outputs:
        if not connected(output):
            config[output] = None
            continue
        config[output] = get_output_config(output, query, last_config)
        last_config = config[output]
    return config


def main():
    query = json.load(sys.stdin)
    config = get_config(query)
    json.dump(config, sys.stdout)


if __name__ == '__main__':
    main()
