---

pkg_state: present

envs:
  pyenv:
    versions:
      - 2.7.14
      - 3.6.4
      - 3.5.5
      - 3.4.8
    packages:
      - pip
      - pip-autoremove
      # virtualenvwrapper depends on pbr.
      - pbr
      - virtualenv
      - virtualenvwrapper
      - twine
      - httpie
      - HTTPolice
      - bumplus
      - qrcode
      - speedtest-cli
      - httpstat
    packages2:
      - ansible
      - netaddr
      # needed by Ansible `ipaddr` filter
      # https://docs.ansible.com/ansible/playbooks_filters_ipaddr.html
      - cryptography
      # needed by Ansible Vault
      # https://docs.ansible.com/ansible/playbooks_vault.html#speeding-up-vault-operations
      - ansible-container
      - ansible-bundle
      - ansible-lint
      - molecule
    packages3:
      - thefuck
      # thefuck drops Python 2 support.  Install it only in Python 3.
      #
      # https://github.com/nvbn/thefuck/issues/685
      - asciinema
      - you-get
  rbenv:
    versions:
      - 2.5.0
      - 2.4.3
      - 2.3.6
      - 2.2.9
    packages:
      - bundler
      - rubocop
      # For Emacs flycheck
      - travis
      - itamae
  nodenv:
    versions:
      # https://github.com/nodejs/LTS#lts-schedule
      - 9.6.1              # Current
      - 8.9.4              # LTS
      - 6.13.0             # LTS
      - 4.8.7              # Maintenance
    packages:
      - npm-run
      - nrm
      - yrm
      - yo
      - json
      - gitbook-cli
      # For Emacs flycheck
      # https://github.com/zaach/jsonlint
      - jsonlint
      - diff-so-fancy
      - prettier
      - eclint

env_versions:
  - name: pyenv
    versions: '{{ envs.pyenv.versions }}'
  - name: rbenv
    versions: '{{ envs.rbenv.versions }}'
  - name: nodenv
    versions: '{{ envs.nodenv.versions }}'

go_packages:
  # dependency management / vendor management
  - github.com/golang/dep/cmd/dep
  - github.com/FiloSottile/gvt
  - github.com/dpw/vendetta
  - github.com/nicerobot/git-freeze
  - github.com/cespare/deplist
  - github.com/kardianos/govendor
  # dev tools
  - golang.org/x/tools/cmd/goimports
  - golang.org/x/tools/cmd/gomvpkg
  - golang.org/x/tools/cmd/gorename
  - github.com/onsi/ginkgo/ginkgo
  - github.com/jteeuwen/go-bindata/go-bindata
  - github.com/elazarl/go-bindata-assetfs/go-bindata-assetfs
  - github.com/alecthomas/gometalinter
  - github.com/shurcooL/binstale
  - github.com/rogpeppe/godef
  - golang.org/x/tools/cmd/guru
  - github.com/tpng/gopkgs
  - github.com/nsf/gocode
  # utils
  - github.com/direnv/direnv
  - github.com/joho/godotenv/cmd/godotenv
  - github.com/cortesi/devd/cmd/devd
  - github.com/google/git-appraise/git-appraise
  - github.com/homburg/git-get
  - github.com/digitalocean/doctl/cmd/doctl
  - github.com/bradleyfalzon/revgrep/cmd/revgrep
  - github.com/schollz/croc
  - github.com/aybabtme/humanlog/cmd/humanlog
  - github.com/gchaincl/httplab/cmd/httplab
  - github.com/google/gops

rust_packages:
  - cargo-update
  - cargo-vendor
  - ripgrep
  - xsv
  - fd-find
