---

pkg_state: present

envs:
  pyenv:
    versions:
      - 2.7.13
      - 3.6.0
      - 3.5.3
      - 3.4.6
    packages:
      - pip
      - pip-autoremove
      # virtualenvwrapper depends on pbr.
      - pbr
      - virtualenv
      - virtualenvwrapper
      - twine
      - httpie
      - HTTPolice
      - bumplus
      - thefuck
      - qrcode
      - speedtest-cli
      - httpstat
    packages2:
      - ansible
      - netaddr
      # needed by Ansible `ipaddr` filter
      # https://docs.ansible.com/ansible/playbooks_filters_ipaddr.html
      - cryptography
      # needed by Ansible Vault
      # https://docs.ansible.com/ansible/playbooks_vault.html#speeding-up-vault-operations
      - ansible-container
      - ansible-bundle
      - ansible-lint
      - molecule
      - offlineimap
      - PySocks
      # needed by offlineimap to use proxy
      # https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf#L437
    packages3:
      - asciinema
  rbenv:
    versions:
      - 2.4.0
      - 2.3.3
      - 2.2.6
    packages:
      - bundler
      - rubocop
      # For Emacs flycheck
      - travis
      - itamae
  nodenv:
    versions:
      # https://github.com/nodejs/LTS#lts-schedule
      - 7.6.0              # Current
      - 6.10.0             # LTS
      - 4.8.0              # LTS
    packages:
      - nrm
      - yo
      - david
      - json
      - gitbook-cli
      # For Emacs flycheck
      # https://github.com/zaach/jsonlint
      - jsonlint

env_versions:
  - name: pyenv
    versions: '{{ envs.pyenv.versions }}'
  - name: rbenv
    versions: '{{ envs.rbenv.versions }}'
  - name: nodenv
    versions: '{{ envs.nodenv.versions }}'

go_packages:
  # dependency management / vendor management
  - github.com/FiloSottile/gvt
  - github.com/dpw/vendetta
  - github.com/nicerobot/git-freeze
  - github.com/cespare/deplist
  - github.com/kardianos/govendor
  # dev tools
  - golang.org/x/tools/cmd/goimports
  - golang.org/x/tools/cmd/gomvpkg
  - github.com/onsi/ginkgo/ginkgo
  - github.com/jteeuwen/go-bindata/...
  - github.com/elazarl/go-bindata-assetfs/...
  - github.com/alecthomas/gometalinter
  - github.com/shurcooL/binstale
  - github.com/rogpeppe/godef
  - golang.org/x/tools/cmd/guru
  # utils
  - github.com/zimbatm/direnv
  - github.com/joho/godotenv/cmd/godotenv
  - github.com/cortesi/devd/cmd/devd
  - github.com/google/git-appraise/git-appraise
  - github.com/homburg/git-get

rust_packages:
  - rustfmt
  - cargo-vendor
