---

pkg_state: present

envs:
  pyenv:
    versions:
      - 2.7.11
      - 3.5.1
    packages:
      - pip
      - pip-autoremove
      # virtualenvwrapper depends on pbr.
      - pbr
      - virtualenv
      - virtualenvwrapper
      - httpie
      - bumpversion
      - thefuck
      - qrcode
      - speedtest-cli
    packages2:
      - ansible
      - ansible-lint
      - molecule
      - 'https://github.com/OfflineIMAP/offlineimap/archive/v6.6.0.zip#egg=offlineimap'
      # OfflineIMAP on PyPI is too old, use Github archive instead.
      - PySocks
      # needed by offlineimap to use proxy
      # https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf#L437
  rbenv:
    versions:
      - 2.3.1
    packages:
      - bundler
      - itamae
  ndenv:
    versions:
      - v6.2.0
      - v4.4.5              # LTS
      - v0.12.14            # LTS / Classic
      - v0.10.45            # Maintenance / Classic
    packages:
      - npm
      - nrm
      - yo
      - david
      - json
      # For Emacs flycheck
      # https://github.com/zaach/jsonlint
      - jsonlint
  goenv:
    versions:
      - 1.6.2
    packages:
      - github.com/zimbatm/direnv
      - github.com/ellotheth/pipethis
      - github.com/jbenet/hashpipe

env_versions:
  - name: pyenv
    versions: '{{ envs.pyenv.versions }}'
  - name: rbenv
    versions: '{{ envs.rbenv.versions }}'
  - name: ndenv
    versions: '{{ envs.ndenv.versions }}'
  - name: goenv
    versions: '{{ envs.goenv.versions }}'
