---
pkg_state: present

envs:
  pyenv:
    # prettier-ignore
    versions:
      # https://en.wikipedia.org/wiki/CPython#Version_history
      - 3.8.0                   # 2024-10
      - 3.7.5                   # 2023-06-27
      - 3.6.9                   # 2021-12-23
      - 3.5.7                   # 2020-09-13
      - 2.7.17                  # 2020-01-01
    packages:
      - pip
      - pipenv
      - pip-autoremove
      - virtualenv
      - virtualenvwrapper
      - httpie
      - bumplus
      - qrcode
      - speedtest-cli
      - caniusepython3
      - autorandr
      - codespell
      - ansible
      - netaddr
      # needed by Ansible `ipaddr` filter
      # https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html
      - cryptography
      # needed by Ansible Vault
      # https://docs.ansible.com/ansible/latest/user_guide/vault.html#speeding-up-vault-operations
      - flake8
      - autoflake
    version_limited_packages:
      - package: black
        match: '^(3\.6\.|3\.7\.|3\.8\.)'
      - package: pyls-black
        match: '^(3\.6\.|3\.7\.|3\.8\.)'
      - package: twine
        match: '^(3\.6\.|3\.7\.|3\.8\.)'
    packages3:
      - thefuck
      # thefuck drops Python 2 support.  Install it only in Python 3.
      #
      # https://github.com/nvbn/thefuck/issues/685
      - asciinema
      - you-get
      - linode-cli
      - HTTPolice
      - isort[requirements,pipfile,pyproject]
      - pyls-isort
      # For flycheck, also install pyflakes, mccabe, pycodestyle for python-language-server.
      - python-language-server[all]
      - molecule
      # Do not install pbr, ansible-lint and yamllint explicitly
      #
      # molecule locks on the dependencies of pbr, ansible-lint, PyYAML and
      # yamllint.  Do not install them explicitly.
  rbenv:
    # prettier-ignore
    versions:
      # https://en.wikipedia.org/wiki/Ruby_(programming_language)#Table_of_versions
      - 2.6.5
      - 2.5.7
    packages:
      - bundler
      - rufo
      - solargraph
      - itamae
  nodenv:
    # prettier-ignore
    versions:
      # https://github.com/nodejs/Release#release-schedule
      - 13.0.1             # 2020-06-01 Current
      - 12.13.0            # 2022-04-30 Active LTS
      - 10.17.0            # 2021-04-30 Active LTS
      - 8.16.2             # 2019-12-31 Maintenance LTS
    npm_packages:
      - npm
      - npm-run
      - nrm
      - yrm
      # Even it's YARN registry manager, it depends on npm.
      - gitbook-cli
    yarn_packages:
      - yo
      - json
      # For Emacs flycheck
      # https://github.com/zaach/jsonlint
      - jsonlint
      - diff-so-fancy
      - prettier
      - eclint
      - lerna
      - git-stats
      - lebab
      - nativefier
      - typescript
      - tslint
      - typescript-language-server
      - flow-bin
      - vscode-html-languageserver-bin
      - vscode-css-languageserver-bin
      - bash-language-server
      - dockerfile-language-server-nodejs
      - vue-language-server
      - git-recall
      - npm-install-peers
  goenv:
    versions:
      - 1.13.3
      - 1.12.12

env_versions:
  - name: pyenv
    versions: '{{ envs.pyenv.versions }}'
  - name: rbenv
    versions: '{{ envs.rbenv.versions }}'
  - name: nodenv
    versions: '{{ envs.nodenv.versions }}'
  - name: goenv
    versions: '{{ envs.goenv.versions }}'

go_vendor_packages:
  # dependency management / vendor management
  # dev tools
  - github.com/oxequa/realize
  # utils
  - github.com/gchaincl/httplab/cmd/httplab

go_module_packages:
  # dependency management / vendor management
  # dev tools
  # utils
  - github.com/davecheney/httpstat

go_gobin_packages:
  # dependency management / vendor management
  - golang.org/x/vgo
  - github.com/FiloSottile/gvt
  - github.com/dpw/vendetta
  - github.com/gomatic/git-freeze
  # dev tools
  - golang.org/x/tools/cmd/goimports
  - golang.org/x/tools/cmd/gomvpkg
  - golang.org/x/tools/cmd/gorename
  - github.com/elazarl/go-bindata-assetfs/go-bindata-assetfs@master
  - github.com/shurcooL/binstale
  - golang.org/x/tools/cmd/guru
  - github.com/stamblerre/gocode@master
  # The official repository is [1]. Go modules support is being added in [2].
  #
  # So we use [2] for now.
  #
  # But note that [2] will be merged into [1] finally.  See [3] for details.
  #
  # [1]: https://github.com/mdempsky/gocode
  # [2]: https://github.com/stamblerre/gocode
  # [3]: https://github.com/mdempsky/gocode/issues/46#issuecomment-427282575
  - github.com/saibing/bingo
  - github.com/cespare/deplist
  # There are 2 variants:
  #
  #  1. https://github.com/cespare/deplist
  #  2. https://github.com/markbates/deplist
  #
  # We use 1 because it requires less dependencies.
  - github.com/rogpeppe/godef
  - github.com/rogpeppe/gohack
  - github.com/uudashr/gopkgs/cmd/gopkgs
  # There are 3 variants:
  #
  #  1. https://github.com/uudashr/gopkgs
  #  2. https://github.com/haya14busa/gopkgs
  #  3. https://github.com/tpng/gopkgs
  #
  # We use 1 because it supports Go modules.
  - github.com/google/gops
  - github.com/ahmetb/govvv@master
  - github.com/sqs/goreturns
  # utils
  - github.com/myitcv/gobin
  - github.com/joho/godotenv/cmd/godotenv@master
  - github.com/homburg/git-get
  - github.com/bradleyfalzon/revgrep/cmd/revgrep
  - github.com/aybabtme/humanlog/cmd/humanlog@master
  - github.com/astaxie/bat@master
  - github.com/rs/jaggr
  - github.com/rs/jplot
  - github.com/cloudflare/cloudflare-go/cmd/flarectl@master

rustup_components:
  - rustfmt
  # https://github.com/rust-lang/rustfmt#quick-start
  - rls-preview rust-analysis rust-src
  # https://github.com/rust-lang/rls#step-2-install-the-rls
  - clippy
  # https://github.com/rust-lang/rust-clippy#step-2-install-clippy

cargo_packages:
  - cargo-update
  - cargo-clone
  - cargo-deb
  - cargo-vendor
  - cargo-ensure-installed
  - fd-find
  - hexyl
  - ripgrep

sdkman_packages:
  - candidate: kotlin
    version: 1.3.21
  - candidate: java
    version: 11.0.2-open
  - candidate: java
    version: 8.0.201-oracle
  - candidate: leiningen
    version: 2.9.1
