---

pkg_state: present

envs:
  pyenv:
    versions:
      # https://en.wikipedia.org/wiki/CPython#Version_history
      - 3.7.1                   # 2023-06-27
      - 3.6.7                   # 2021-12-23
      - 3.5.6                   # 2020-09-13
      - 3.4.9                   # 2019-03-16
      - 2.7.15                  # 2020-01-01
    packages:
      - pip
      - pipenv
      - pip-autoremove
      - virtualenv
      - virtualenvwrapper
      - twine
      - python-language-server
      - httpie
      # https://github.com/requests/requests/issues/4246#issuecomment-356336986
      - pyOpenSSL
      - HTTPolice
      - bumplus
      - qrcode
      - speedtest-cli
      - httpstat
      - caniusepython3
      - autorandr
      - ansible
      - netaddr
      # needed by Ansible `ipaddr` filter
      # https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html
      - cryptography
      # needed by Ansible Vault
      # https://docs.ansible.com/ansible/latest/user_guide/vault.html#speeding-up-vault-operations
      - git+https://github.com/ansible/ansible-container.git@develop
      # Workaround of `ImportError: No module named 'pip.req'`
      #
      # https://github.com/ansible/ansible-container/issues/919#issuecomment-401142364
      - molecule
      # Do not install pbr, ansible-lint and yamllint explicitly
      #
      # molecule locks on the dependencies of pbr, ansible-lint, PyYAML and
      # yamllint.  Do not install them explicitly.
    packages2:
      - ansible-bundle
    packages3:
      - thefuck
      # thefuck drops Python 2 support.  Install it only in Python 3.
      #
      # https://github.com/nvbn/thefuck/issues/685
      - asciinema
      - you-get
      - linode-cli
  rbenv:
    versions:
      # https://en.wikipedia.org/wiki/Ruby_(programming_language)#Table_of_versions
      - 2.5.3
      - 2.4.5
      - 2.3.8                   # 2019-03-31
    packages:
      - bundler
      - rubocop
      # For Emacs flycheck
      - solargraph
      - travis
      - itamae
  nodenv:
    versions:
      # https://github.com/nodejs/Release#release-schedule
      - 11.1.0             # 2019-06 Current
      - 10.13.0            # 2021-04 LTS
      - 8.12.0             # 2019-12 LTS
      - 6.14.4             # 2019-04 Maintenance
    npm_packages:
      - npm
      - npm-run
      - nrm
      - yrm
      # Even it's YARN registry manager, it depends on npm.
      - gitbook-cli
      - strapi@alpha
      # https://github.com/strapi/strapi/issues/1798
    yarn_packages:
      - yo
      - json
      # For Emacs flycheck
      # https://github.com/zaach/jsonlint
      - jsonlint
      - diff-so-fancy
      - prettier
      - eclint
      - lerna
      - git-stats
      - lebab
      - nativefier
      - flow-language-server
      - vscode-html-languageserver-bin
      - vscode-css-languageserver-bin
      - bash-language-server
      - dockerfile-language-server-nodejs
      - vue-language-server
  goenv:
    versions:
      - 1.11.2
      - 1.10.5

env_versions:
  - name: pyenv
    versions: '{{ envs.pyenv.versions }}'
  - name: rbenv
    versions: '{{ envs.rbenv.versions }}'
  - name: nodenv
    versions: '{{ envs.nodenv.versions }}'
  - name: goenv
    versions: '{{ envs.goenv.versions }}'

go_packages:
  # dependency management / vendor management
  - github.com/golang/dep/cmd/dep
  - golang.org/x/vgo
  - github.com/FiloSottile/gvt
  - github.com/dpw/vendetta
  - github.com/nicerobot/git-freeze
  - github.com/cespare/deplist
  - github.com/kardianos/govendor
  # dev tools
  - golang.org/x/tools/cmd/goimports
  - golang.org/x/tools/cmd/gomvpkg
  - golang.org/x/tools/cmd/gorename
  - github.com/jteeuwen/go-bindata/go-bindata
  - github.com/elazarl/go-bindata-assetfs/go-bindata-assetfs
  - github.com/alecthomas/gometalinter
  - github.com/shurcooL/binstale
  - github.com/rogpeppe/godef
  - golang.org/x/tools/cmd/guru
  - github.com/tpng/gopkgs
  - github.com/nsf/gocode
  - github.com/sourcegraph/go-langserver
  # utils
  - github.com/direnv/direnv
  - github.com/joho/godotenv/cmd/godotenv
  - github.com/cortesi/devd/cmd/devd
  - github.com/cortesi/modd/cmd/modd
  - github.com/google/git-appraise/git-appraise
  - github.com/homburg/git-get
  - github.com/digitalocean/doctl/cmd/doctl
  - github.com/bradleyfalzon/revgrep/cmd/revgrep
  - github.com/schollz/croc
  - github.com/aybabtme/humanlog/cmd/humanlog
  - github.com/gchaincl/httplab/cmd/httplab
  - github.com/google/gops
  - github.com/JamesClonk/vultr
  - github.com/spolu/warp/client/cmd/warp
  - github.com/github/git-sizer
  - github.com/jedisct1/piknik

rust_packages:
  - cargo-update
  - cargo-deb
  - cargo-vendor
  - cargo-ensure-installed
  - ripgrep
  - xsv
  - fd-find
