---
pkg_state: present

envs:
  pyenv:
    # prettier-ignore
    versions:
      # https://en.wikipedia.org/wiki/CPython#Version_history
      - 3.7.2                   # 2023-06-27
      - 3.6.8                   # 2021-12-23
      - 3.5.6                   # 2020-09-13
      - 3.4.9                   # 2019-03-16
      - 2.7.15                  # 2020-01-01
    packages:
      - pip
      - pipenv
      - pip-autoremove
      - virtualenv
      - virtualenvwrapper
      - twine
      - python-language-server[all]
      - httpie
      # https://github.com/requests/requests/issues/4246#issuecomment-356336986
      - pyOpenSSL
      - HTTPolice
      - bumplus
      - qrcode
      - speedtest-cli
      - httpstat
      - caniusepython3
      - autorandr
      - codespell
      - ansible
      - netaddr
      # needed by Ansible `ipaddr` filter
      # https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html
      - cryptography
      # needed by Ansible Vault
      # https://docs.ansible.com/ansible/latest/user_guide/vault.html#speeding-up-vault-operations
      - git+https://github.com/ansible/ansible-container.git@develop#egg=ansible-container[docker]
      # Workaround of `ImportError: No module named 'pip.req'`
      #
      # https://github.com/ansible/ansible-container/issues/919#issuecomment-433524170
      - molecule
      # Do not install pbr, ansible-lint and yamllint explicitly
      #
      # molecule locks on the dependencies of pbr, ansible-lint, PyYAML and
      # yamllint.  Do not install them explicitly.
      - git+https://github.com/timothycrosley/isort.git@develop#egg=isort[requirements,pipfile,pyproject]
      # Stable version is too old.
      #
      # https://github.com/timothycrosley/isort/issues/760
    version_limited_packages:
      - package: black
        match: '^(3\.6\.|3\.7\.)'
    packages2:
      - ansible-bundle
    packages3:
      - thefuck
      # thefuck drops Python 2 support.  Install it only in Python 3.
      #
      # https://github.com/nvbn/thefuck/issues/685
      - asciinema
      - you-get
      - linode-cli
  rbenv:
    # prettier-ignore
    versions:
      # https://en.wikipedia.org/wiki/Ruby_(programming_language)#Table_of_versions
      - 2.6.1
      - 2.5.3
      - 2.4.5
      - 2.3.8                   # 2019-03-31
    packages:
      - bundler
      - rufo
      - solargraph
      - travis
      - itamae
  nodenv:
    # prettier-ignore
    versions:
      # https://github.com/nodejs/Release#release-schedule
      - 11.10.0            # 2019-06 Current
      - 10.15.1            # 2021-04 LTS
      - 8.15.0             # 2019-12 LTS
      - 6.16.0             # 2019-04 Maintenance
    npm_packages:
      - npm
      - npm-run
      - nrm
      - yrm
      # Even it's YARN registry manager, it depends on npm.
      - gitbook-cli
    yarn_packages:
      - yo
      - json
      # For Emacs flycheck
      # https://github.com/zaach/jsonlint
      - jsonlint
      - diff-so-fancy
      - prettier
      - eclint
      - lerna
      - git-stats
      - lebab
      - nativefier
      - typescript
      - tslint
      - typescript-language-server
      - flow-bin
      - vscode-html-languageserver-bin
      - vscode-css-languageserver-bin
      - bash-language-server
      - dockerfile-language-server-nodejs
      - vue-language-server
  goenv:
    versions:
      - 1.11.5
      - 1.10.8

env_versions:
  - name: pyenv
    versions: '{{ envs.pyenv.versions }}'
  - name: rbenv
    versions: '{{ envs.rbenv.versions }}'
  - name: nodenv
    versions: '{{ envs.nodenv.versions }}'
  - name: goenv
    versions: '{{ envs.goenv.versions }}'

go_get_packages:
  # dependency management / vendor management
  - golang.org/x/vgo
  - github.com/FiloSottile/gvt
  - github.com/dpw/vendetta
  - github.com/gomatic/git-freeze
  # dev tools
  - golang.org/x/tools/cmd/goimports
  - golang.org/x/tools/cmd/gomvpkg
  - golang.org/x/tools/cmd/gorename
  - github.com/elazarl/go-bindata-assetfs/go-bindata-assetfs
  - github.com/shurcooL/binstale
  - golang.org/x/tools/cmd/guru
  - github.com/mdempsky/gocode
  # The official repository is [1]. Go modules support is being added in [2].
  #
  # Because [2] will be merged into [1] finally.  We use [1].
  #
  # See [3] for details.
  #
  # [1]: https://github.com/mdempsky/gocode
  # [2]: https://github.com/stamblerre/gocode
  # [3]: https://github.com/mdempsky/gocode/issues/46#issuecomment-427282575
  - github.com/sourcegraph/go-langserver
  # utils
  - github.com/joho/godotenv/cmd/godotenv
  - github.com/homburg/git-get
  - github.com/bradleyfalzon/revgrep/cmd/revgrep
  - github.com/aybabtme/humanlog/cmd/humanlog
  - github.com/gchaincl/httplab/cmd/httplab

rustup_components:
  - rustfmt
  # https://github.com/rust-lang/rustfmt#quick-start
  - rls-preview rust-analysis rust-src
  # https://github.com/rust-lang/rls#step-2-install-the-rls
  - clippy
  # https://github.com/rust-lang/rust-clippy#step-2-install-clippy

rust_packages:
  - cargo-update
  - cargo-deb
  - cargo-vendor
  - cargo-ensure-installed
  - fd-find
  - hexyl
