---

pkg_state: present

envs:
  pyenv:
    versions:
      - 2.7.12
      - 3.5.2
    packages:
      - pip
      - pip-autoremove
      # virtualenvwrapper depends on pbr.
      - pbr
      - virtualenv
      - virtualenvwrapper
      - twine
      - httpie
      - bumpversion
      - thefuck
      - qrcode
      - speedtest-cli
    packages2:
      - ansible
      - netaddr
      # needed by Ansible `ipaddr` filter
      # https://docs.ansible.com/ansible/playbooks_filters_ipaddr.html
      - cryptography
      # needed by Ansible Vault
      # https://docs.ansible.com/ansible/playbooks_vault.html#speeding-up-vault-operations
      - ansible-lint
      - molecule
      - 'https://github.com/OfflineIMAP/offlineimap/archive/v6.6.0.zip#egg=offlineimap'
      # OfflineIMAP on PyPI is too old, use Github archive instead.
      - PySocks
      # needed by offlineimap to use proxy
      # https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf#L437
  rbenv:
    versions:
      - 2.3.1
    packages:
      - bundler
      - itamae
  ndenv:
    versions:
      - v6.5.0              # Current
      - v5.12.0             # Stable
      - v4.5.0              # LTS
      - v0.12.15            # Maintenance
      - v0.10.46            # Maintenance
    packages:
      - npm
      - nrm
      - yo
      - david
      - json
      # For Emacs flycheck
      # https://github.com/zaach/jsonlint
      - jsonlint
  goenv:
    versions:
      - 1.7
    packages:
      - github.com/zimbatm/direnv
      - github.com/ellotheth/pipethis
      - github.com/jbenet/hashpipe
      - github.com/asciinema/asciinema
      - github.com/joho/godotenv/cmd/godotenv
      - github.com/onsi/ginkgo/ginkgo
      - github.com/FiloSottile/gvt
      - github.com/dpw/vendetta
      - github.com/nicerobot/git-freeze
      - github.com/govend/govend
      - github.com/cespare/deplist
      - github.com/cortesi/devd/cmd/devd

env_versions:
  - name: pyenv
    versions: '{{ envs.pyenv.versions }}'
  - name: rbenv
    versions: '{{ envs.rbenv.versions }}'
  - name: ndenv
    versions: '{{ envs.ndenv.versions }}'
  - name: goenv
    versions: '{{ envs.goenv.versions }}'
