---

pkg_state: present

envs:
  pyenv:
    versions:
      - 2.7.12
      - 3.5.2
      - 3.4.5
    packages:
      - pip
      - pip-autoremove
      # virtualenvwrapper depends on pbr.
      - pbr
      - virtualenv
      - virtualenvwrapper
      - twine
      - httpie
      - HTTPolice
      - bumplus
      - thefuck
      - qrcode
      - speedtest-cli
    packages2:
      - ansible
      - netaddr
      # needed by Ansible `ipaddr` filter
      # https://docs.ansible.com/ansible/playbooks_filters_ipaddr.html
      - cryptography
      # needed by Ansible Vault
      # https://docs.ansible.com/ansible/playbooks_vault.html#speeding-up-vault-operations
      - ansible-container
      - ansible-lint
      - molecule
      - 'https://github.com/OfflineIMAP/offlineimap/archive/v7.0.8.zip#egg=offlineimap'
      # OfflineIMAP on PyPI is too old, use Github archive instead.
      - PySocks
      # needed by offlineimap to use proxy
      # https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf#L437
    packages3:
      - asciinema
  rbenv:
    versions:
      - 2.3.3
      - 2.2.6
    packages:
      - bundler
      - rubocop
      # For Emacs flycheck
      - travis
      - itamae
  nodenv:
    versions:
      # https://github.com/nodejs/LTS#lts-schedule
      - 7.2.1              # Current
      - 6.9.2              # LTS
      - 4.7.0              # LTS
    packages:
      - npm
      - yarn
      - nrm
      - yo
      - david
      - json
      - gitbook-cli
      # For Emacs flycheck
      # https://github.com/zaach/jsonlint
      - jsonlint
  goenv:
    versions:
      - 1.7.4
    packages:
      # dependency management / vendor management
      - github.com/FiloSottile/gvt
      - github.com/dpw/vendetta
      - github.com/nicerobot/git-freeze
      - github.com/cespare/deplist
      - github.com/kardianos/govendor
      # dev tools
      - golang.org/x/tools/cmd/goimports
      - golang.org/x/tools/cmd/gomvpkg
      - github.com/onsi/ginkgo/ginkgo
      - github.com/jteeuwen/go-bindata/...
      - github.com/elazarl/go-bindata-assetfs/...
      - github.com/alecthomas/gometalinter
      - github.com/shurcooL/binstale
      # utils
      - github.com/zimbatm/direnv
      - github.com/joho/godotenv/cmd/godotenv
      - github.com/cortesi/devd/cmd/devd
      - github.com/google/git-appraise/git-appraise
      - github.com/homburg/git-get

env_versions:
  - name: pyenv
    versions: '{{ envs.pyenv.versions }}'
  - name: rbenv
    versions: '{{ envs.rbenv.versions }}'
  - name: nodenv
    versions: '{{ envs.nodenv.versions }}'
  - name: goenv
    versions: '{{ envs.goenv.versions }}'
