---
- name: update apt cache
  apt:
    update_cache: yes

- name: reload systemd
  command: systemctl daemon-reload

- name: restart docker
  command: systemctl restart docker.service

- name: restart syncthing
  command: 'systemctl restart syncthing@{{ hostvars[inventory_hostname].ansible_user }}.service'
  # Syncthing doesn't support reload for systemd.  Restart it instead.

- name: reload udev
  command: udevadm control --reload-rules

- name: restart udev
  command: systemctl restart udev.service
