---
terraform_system: '{{ ansible_system | lower }}'
terraform_arch: '{{ ansible_architecture | lower }}'
terraform_package_filename: 'terraform_{{ terraform_version }}_{{ terraform_system }}_{{ terraform_arch }}.zip'
