dotfiles:
  area: default
  roles: []
  roleData:
    default:
      httpProxy: ""
      httpsProxy: ""
      editor: emacsclient
      alternateEditor: vim
      alternateGraphicEditor: gvim
      name: Wade Zhang
      email: dochang@gmail.com
      mailuser: dochang
      mailhost: localhost
      maildir: /srv/sync/maildir
      passwordStoreDir: "${HOME}/.password-store"
      gitCredential: dochang
      gitUserName: Wade Zhang
      gitUserEmail: dochang@gmail.com
  areaData:
    default:
      nodejsOrgMirror: "https://nodejs.org/dist"
      # https://github.com/nodejs/node-gyp/blob/v7.0.0/lib/process-release.js#L65-L67
      nodeBuildMirrorURL: "https://nodejs.org/dist"
      # https://github.com/nodejs/node-gyp/blob/v7.0.0/lib/process-release.js#L76
      sassBinarySite: "https://github.com/sass/node-sass/releases/download"
      # https://github.com/sass/node-sass/blob/v4.14.1/lib/extensions.js#L247
      electronMirror: "https://github.com/electron/electron/releases/download/"
      electronCustomDir: "v{{ version }}"
      # https://www.electronjs.org/docs/latest/tutorial/installation#mirror
      # https://github.com/electron/get/blob/a0d0ea97850950a8a5a21a510cd4d9514af66a64/src/artifact-utils.ts#L47
      # https://github.com/electron/get/blob/a0d0ea97850950a8a5a21a510cd4d9514af66a64/src/artifact-utils.ts#L4
      puppeteerDownloadHost: "https://storage.googleapis.com"
      # https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#environment-variables
      # https://github.com/puppeteer/puppeteer/commit/945a826a0b53bb7325fdb86c998f812b16032c37
      homebrewBottleDomain: "https://linuxbrew.bintray.com"
      homebrewBrewGitRemote: "https://github.com/Homebrew/brew"
      homebrewCoreGitRemote: "https://github.com/Homebrew/linuxbrew-core"
      pythonBuildMirrorURL: "https://pyenv.github.io/pythons"
      pythonBuildMirrorURLSkipChecksum: ""
      # - With mirror set and "skip checksum" set, download from mirror of the official source ("www.python.org/ftp/python")
      # - With mirror unset and "skip checksum" unset, download from "pyenv mirror" ("https://pyenv.github.io/pythons")
      # - With mirror set and "skip checksum" unset, download from mirror of "pyenv mirror" ("https://pyenv.github.io/pythons")
      goproxy: "https://proxy.golang.org,direct"
      gosumdb: "sum.golang.org"
      rustupDistServer: "https://static.rust-lang.org"
      rustupUpdateRoot: "https://static.rust-lang.org/rustup"
      # https://doc.rust-lang.org/cargo/reference/source-replacement.html
      # https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/registry/mod.rs#L185
      # https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/config.rs#L48
      gemSource:
        "BUNDLE_MIRROR__HTTPS://RUBYGEMS__ORG/": "https://rubygems.org/"
      cargoSource:
        "crates-io":
          registry: "https://github.com/rust-lang/crates.io-index"
      # https://doc.rust-lang.org/cargo/reference/source-replacement.html
      # https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/registry/mod.rs#L185
      # https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/config.rs#L48
      cargoRegistries: {}
      # https://doc.rust-lang.org/cargo/reference/registries.html
      gradleRepos:
        - type: mavenLocal
        - type: mavenCentral
      # https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.repositories.MavenArtifactRepository.html
      # https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.RepositoryHandler.html
      # https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.RepositoryHandler.html#org.gradle.api.artifacts.dsl.RepositoryHandler:maven(groovy.lang.Closure)
      # https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.RepositoryHandler.html#org.gradle.api.artifacts.dsl.RepositoryHandler:maven(org.gradle.api.Action)
      # https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.RepositoryHandler.html#org.gradle.api.artifacts.dsl.RepositoryHandler:mavenCentral()
      # https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.RepositoryHandler.html#org.gradle.api.artifacts.dsl.RepositoryHandler:mavenCentral(java.util.Map)
      # https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.RepositoryHandler.html#org.gradle.api.artifacts.dsl.RepositoryHandler:mavenCentral(org.gradle.api.Action)
      # https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.RepositoryHandler.html#org.gradle.api.artifacts.dsl.RepositoryHandler:mavenLocal()
      # https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.RepositoryHandler.html#org.gradle.api.artifacts.dsl.RepositoryHandler:mavenLocal(org.gradle.api.Action)
      mavenMirrors: []
      npmRegistry: "https://registry.npmjs.org/"
      npmDisturl: "https://nodejs.org/dist"
      # https://github.com/nodejs/node-gyp/blob/v7.0.0/lib/process-release.js#L22
      pbuilderMirrorsite: "http://deb.debian.org/debian"
      pipIndexURL: "https://pypi.org/simple"
    cn:
      nodejsOrgMirror: "https://npmmirror.com/mirrors/node"
      nodeBuildMirrorURL: "https://npmmirror.com/mirrors/node"
      sassBinarySite: "https://npmmirror.com/mirrors/node-sass"
      # https://npmmirror.com/mirrors
      electronMirror: "http://npmmirror.com/mirrors/electron/"
      electronCustomDir: "{{ version }}"
      # https://www.electronjs.org/docs/latest/tutorial/installation#mirror
      # https://npmmirror.com/
      # https://npmmirror.com/mirrors/
      puppeteerDownloadHost: "https://npmmirror.com/mirrors"
      homebrewBottleDomain: "https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles"
      homebrewBrewGitRemote: "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
      homebrewCoreGitRemote: "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
      # https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/
      pythonBuildMirrorURL: "https://npmmirror.com/mirrors/python/"
      pythonBuildMirrorURLSkipChecksum: "1"
      goproxy: "https://goproxy.cn,direct"
      # https://golang.org/cmd/go/#hdr-Module_authentication_failures
      # https://github.com/golang/go/issues/31755#issuecomment-527611727
      gosumdb: "sum.golang.google.cn"
      rustupDistServer: "https://rsproxy.cn"
      rustupUpdateRoot: "https://rsproxy.cn/rustup"
      # https://rsproxy.cn/
      # https://doc.crates.io/source-replacement.html
      # https://doc.rust-lang.org/cargo/reference/source-replacement.html
      gemSource:
        "BUNDLE_MIRROR__HTTPS://RUBYGEMS__ORG/": "https://gems.ruby-china.com/"
      # Reduce transfer from ustc mirror.
      #
      # dotfiles_gem_source:
      #   'BUNDLE_MIRROR__HTTPS://RUBYGEMS__ORG/': 'https://mirrors.ustc.edu.cn/rubygems/'
      cargoSource:
        "crates-io":
          registry: ""
          replace-with: rsproxy
        rsproxy:
          registry: "https://rsproxy.cn/crates.io-index"
        tuna:
          registry: "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"
      # https://rsproxy.cn/
      # https://doc.crates.io/source-replacement.html
      # https://doc.rust-lang.org/cargo/reference/source-replacement.html
      cargoRegistries:
        rsproxy:
          index: "https://rsproxy.cn/crates.io-index"
      # https://doc.rust-lang.org/cargo/reference/registries.html
      gradleRepos:
        - type: mavenLocal
        - type: maven
          name: aliyunmaven
          url: https://maven.aliyun.com/repository/public/
        - type: mavenCentral
      mavenMirrors:
        - id: aliyunmaven
          mirrorOf: central,jcenter
          name: Aliyun Maven
          url: https://maven.aliyun.com/repository/public
      # https://www.jianshu.com/p/7fe6c7ab74f6
      # https://help.aliyun.com/document_detail/102512.html
      # http://mirrors.163.com/.help/maven.html
      npmRegistry: "https://registry.npmmirror.com"
      npmDisturl: "https://npmmirror.com/mirrors/node"
      pbuilderMirrorsite: "https://mirrors.ustc.edu.cn/debian"
      pipIndexURL: "https://pypi.doubanio.com/simple"
