#!/bin/sh -l
# -*- mode: sh -*-

if [ -e /etc/X11/Xsession ]; then
	if [ -x /etc/X11/Xsession ]; then
		exec /etc/X11/Xsession
	else
		. /etc/X11/Xsession
	fi
else
	USRRESOURCES=$HOME/.Xresources
	USERXSESSION=$HOME/.xsession
	USERXSESSIONRC=$HOME/.xsessionrc
	ALTUSERXSESSION=$HOME/.Xsession
	ERRFILE=$HOME/.xsession-errors

	: >"$ERRFILE"

	SESSIONFILES=$(find $HOME/.Xsession.d -not -type d)
	if [ -n "$SESSIONFILES" ]; then
		set +e
		for SESSIONFILE in $HOME/.Xsession.d/*; do
			. $SESSIONFILE
		done
		set -e
	fi
fi
