#!/bin/sh -l
# -*- mode: sh -*-

# `.xsession` has to be invoked by `/bin/sh -l`, because `/bin/sh`
# loaded environment variables with `-l`.

# Customization
export XLOCKER="i3lock -c 000000"

export XMODIFIERS="@im=none"
# `local` or `none`
#
# https://gitlab.freedesktop.org/xorg/lib/libx11/-/blob/libX11-1.8.12/modules/im/ximcp/imLcIm.c?ref_type=tags#L96-118

o input

xsetroot -cursor_name left_ptr

# turn off system beep
# http://www.debian-administration.org/articles/110
xset b off

if command -v autorandr >/dev/null 2>&1; then
	autorandr --change
fi

o autostart

STARTUP="${X_WINDOW_MANAGER:-x-window-manager}"

STARTUP="env SHELL=$(getent passwd $LOGNAME | cut -d: -f7) $STARTUP"
# `SHELL` should be `/bin/sh` until now since `/bin/sh` is invoked
# with `-l`.  Here it will be overridden by getting the login shell
# from `getent`.  According to `login(1)`, the user's name should be
# taken from `$LOGNAME`.

STARTUP="o X $STARTUP"

eval "$STARTUP"
